name: Change Tracking Marker
on:
  push:
    branches:
      - main

jobs:
  atatus:
    runs-on: ubuntu-latest
    name: Atatus
    steps:
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Get tag version if available
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_VERSION="${GITHUB_REF##*/}"
            echo "Tag version: $TAG_VERSION"
            echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          else
            echo "No tag version for this commit"
          fi
      # - name: Get Commit Message
      #   id: commit_message
      #   run: ||
      #     # Fetch the commit message for the current commit (GITHUB_SHA)
      #     COMMIT_MSG=$(git log -1 --pretty=%B $GITHUB_SHA)
      #     echo "Commit message: $COMMIT_MSG"

      #     echo "COMMIT_MESSAGE=$COMMIT_MSG" >> $GITHUB_ENV te


      # This step creates a new Change Tracking Marker
      - name: Atatus Application Deployment Marker
        uses: atatus/deployment-marker-action@v1.0.1
        with:
          apiKey: ${{ secrets.ATATUS_API_KEY }}
          projectId: ${{ secrets.ATATUS_PROJECT_ID }}
          revision: ${{ env.TAG_VERSION || github.run_number }}
          releaseStage: 'staging'
          changes: ${{ github.sha }}
          user: ${{ github.actor }}