name: Change Tracking Marker
on:
  push:
    branches:
      - main

jobs:
  atatus:
    runs-on: ubuntu-latest
    name: Atatus
    steps:
      - name: Get Commit Message
        id: commit_message
        run: |
          # Fetch the commit message for the current commit (GITHUB_SHA)
          COMMIT_MSG=${{ github.event.workflow_run.head_commit.message }}
          echo "Commit message: $COMMIT_MSG"

          echo "COMMIT_MESSAGE=$COMMIT_MSG" >> $GITHUB_ENV

      # This step creates a new Change Tracking Marker
      - name: Atatus Application Deployment Marker
        uses: atatus/deployment-marker-action@v1.0.1
        with:
          apiKey: ${{ secrets.ATATUS_API_KEY }}
          projectId: ${{ secrets.ATATUS_PROJECT_ID }}
          revision: ${{ github.run_number }}
          releaseStage: 'production'
          changes: ${{ env.COMMIT_MESSAGE }}
          user: ${{ github.actor }}