name: Change Tracking Marker
# on:
#   push:
#     branches:
#       - main
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  atatus:
    runs-on: ubuntu-latest
    name: Atatus
    steps:
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Atatus Application Deployment Marker
        uses: atatus/deployment-marker-action@v1.0.2
        with:
          apiKey: ${{ secrets.ATATUS_API_KEY }}
          projectId: ${{ secrets.ATATUS_PROJECT_ID }}
          revision: ${{ env.RELEASE_VERSION || github.run_number }}
          releaseStage: 'production'
          changes: ${{ github.sha }}
          user: ${{ github.actor }}